# Generated by Django 4.2.16 on 2026-03-27 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_organization_created_at_alter_organization_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activitylog',
            name='audit_activ_organiz_6944a2_idx',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='object_repr',
            field=models.CharField(default='', help_text="Human-readable snapshot of the record at action time (e.g. 'Acme Corp'). Persists after soft delete.", max_length=255),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], help_text='Type of mutation: CREATE, UPDATE, or DELETE.', max_length=10),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='model_name',
            field=models.CharField(help_text="Python class name of the affected model, e.g. 'Company' or 'Contact'.", max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='object_id',
            field=models.CharField(help_text='UUID (as string) of the affected record.', max_length=36),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='organization',
            field=models.ForeignKey(help_text='Tenant owner. Scopes the log to the correct organization.', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='UTC timestamp of the action. Set once, never modified.'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(help_text='The user who triggered the action. SET_NULL on user deletion so the log is never orphaned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['organization', 'timestamp'], name='auditlog_org_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['organization', 'action'], name='auditlog_org_action_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['model_name', 'object_id'], name='auditlog_model_object_idx'),
        ),
        migrations.AlterModelTable(
            name='activitylog',
            table='audit_activity_logs',
        ),
    ]
