# Generated by Django 4.2.16 on 2026-03-27 02:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Immutable creation timestamp set by the database.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID PK. Not auto-incremented so tenant IDs cannot be guessed.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='Display name of the organization. Must be globally unique.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro')], default='basic', help_text='Subscription tier. Drives feature gating in future iterations.', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Primary login credential. Unique across the entire system.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(help_text='Display name shown in the UI and audit logs.', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft-deactivation flag. Deactivated users cannot log in.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text="Grants access to the /admin/ site. Not related to the 'Staff' role."),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The tenant this user belongs to. Null only for Django superusers.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff')], default='staff', help_text='Determines what actions the user can perform (RBAC).', max_length=10),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'role'], name='users_organiz_6045b8_idx'),
        ),
        migrations.AlterModelTable(
            name='organization',
            table='organizations',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
