# Generated by Django 4.2.16 on 2026-03-27 02:34

import apps.crm.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_organization_created_at_alter_organization_id_and_more'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='company',
            new_name='company_org_deleted_idx',
            old_name='crm_company_organiz_2354ee_idx',
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='contact_org_deleted_idx',
            old_name='crm_contact_organiz_e22219_idx',
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='contact_company_deleted_idx',
            old_name='crm_contact_company_f493ac_idx',
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, default='', help_text='Country of headquarters. ISO alpha-2 or full name. Optional.', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Set once on creation. Never modified.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, default='', help_text="Industry sector (e.g. 'Technology', 'Finance'). Optional.", max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. TenantScopedMixin always filters is_deleted=False.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo. Stored on S3 in production. Served via pre-signed URLs — bucket is private.', null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Company display name. Unique within the organization.', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='organization',
            field=models.ForeignKey(help_text='Tenant owner. Every query MUST filter by this field.', on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated automatically on every save().'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(help_text='The parent company this contact belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.company'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(help_text='Must be a valid email format. Unique within the same company (partial constraint, active only).', max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(help_text="Contact's full display name.", max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. Filtered out by TenantScopedMixin.'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(help_text='Denormalized tenant key. Copied from company.organization on create by CompanyContactCreateSerializer. Never editable by the client.', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Optional. 8–15 consecutive digits. No spaces or symbols.', max_length=15, validators=[apps.crm.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(blank=True, default='', help_text='Job title or role at the company. Optional free-text.', max_length=100),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['organization', 'name'], name='company_org_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'name'), name='unique_active_company_name_per_org'),
        ),
        migrations.AlterModelTable(
            name='company',
            table='crm_companies',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='crm_contacts',
        ),
    ]
